import React,{useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {NotebookPen,LogOut,Users,HardDrive,X,Copy} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogClose} from '@/components/ui/dialog';
import Workspace from './workspace';
import './globals.css';
import './local.css';
type User={userId:string;email:string;name:string;role:'owner'|'member'};
async function api(url:string,method='GET',body?:unknown){const r=await fetch(url,{method,headers:{'Content-Type':'application/json'},...(body!==undefined?{body:JSON.stringify(body)}:{})});const result=await r.json();if(!r.ok)throw new Error(result.error||'请求失败');return result;}
function App(){
 const [user,setUser]=useState<User|null>(null),[setup,setSetup]=useState(false),[ready,setReady]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[members,setMembers]=useState(false);
 const [invitation]=useState(()=>new URLSearchParams(location.hash.slice(1)));
 const [register,setRegister]=useState(invitation.has('invite'));
 const [email,setEmail]=useState(invitation.get('email')||''),[name,setName]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState('');
 const refresh=async()=>{const d=await api('/api/session');setUser(d.user);setSetup(d.setupRequired);setReady(true);setError('');};
 useEffect(()=>{if(location.hash)history.replaceState(null,'',location.pathname);void refresh().catch(e=>{setError(e.message);setReady(true);});},[]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');if((setup||register)&&password!==confirm){setError('两次输入的密码不一致');return;}setBusy(true);try{await api(setup?'/api/setup':register?'/api/register':'/api/login','POST',{email,name,password,token:invitation.get('invite')});setPassword('');setConfirm('');await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 if(!ready)return <div className="local-login"><p>正在打开本地工作台…</p></div>;
 if(!user)return <main className="local-login"><section className="login-card"><div className="local-brand"><span className="brand-mark"><NotebookPen size={24}/></span><div><h1>日序</h1><p>本地工作台</p></div></div><h2>{setup?'创建你的管理员账号':register?'接受邀请':'欢迎回来'}</h2><p className="login-description">{setup?'设置本地账号，开始记录日程、科研进展和灵感。':register?'请使用受邀邮箱创建账号。你的记录会独立保存。':'登录后继续记录今天的进展。'}</p><form onSubmit={submit}><fieldset disabled={busy}>{(setup||register)&&<label className="form-field">称呼<input required maxLength={80} autoComplete="name" value={name} onChange={e=>setName(e.target.value)}/></label>}<label className="form-field">邮箱<input type="email" autoComplete="username" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="form-field">{setup||register?'设置密码（至少 12 个字符）':'密码'}<input type="password" autoComplete={setup||register?'new-password':'current-password'} required minLength={setup||register?12:1} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)}/></label>{(setup||register)&&<label className="form-field">确认密码<input type="password" autoComplete="new-password" required minLength={12} maxLength={128} value={confirm} onChange={e=>setConfirm(e.target.value)}/></label>}{error&&<div className="error" role="alert">{error}</div>}<button className="primary login-submit" type="submit">{busy?'正在处理…':setup?'创建并进入工作台':register?'接受邀请并创建账号':'登录'}</button></fieldset></form>{register&&!setup&&<button className="text-btn login-switch" onClick={()=>{setRegister(false);setError('');}}>已有账号，前往登录</button>}<div className="local-note"><HardDrive size={16}/><span>数据保存在这台电脑 · 无需 ChatGPT 登录</span></div></section></main>;
 return <><Workspace signedIn displayName={user.name} accountTools={<><span className="account-name"><HardDrive size={15}/>{user.name} · 本地保存</span>{user.role==='owner'&&<button className="text-btn" onClick={()=>setMembers(true)}><Users size={16}/>成员与邀请</button>}<button className="text-btn" onClick={async()=>{if(busy)return;setBusy(true);try{await api('/api/session','DELETE');setUser(null);setRegister(false);setMembers(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><LogOut size={15}/>退出登录</button>{error&&<span role="alert" className="account-error">{error}</span>}</>}/>{members&&<Members onClose={()=>setMembers(false)}/>}</>;
}
function Members({onClose}:{onClose:()=>void}){
 const [email,setEmail]=useState(''),[link,setLink]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[copied,setCopied]=useState(false);
 const [data,setData]=useState<{users:{id:string;name:string;email:string;role:string;active:number}[];invitations:{id:string;email:string;expires:number}[]}>({users:[],invitations:[]});
 const load=async()=>setData(await api('/api/invitations'));useEffect(()=>{void load().catch(e=>setError(e.message));},[]);
 const action=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <Dialog open onOpenChange={open=>{if(!open&&!busy)onClose();}}><DialogContent className="modal member-modal" showCloseButton={false}><div className="modal-head"><DialogTitle>成员与邀请</DialogTitle><DialogClose asChild><button aria-label="关闭成员管理" className="iconbtn" disabled={busy}><X/></button></DialogClose></div><DialogDescription>受邀账号各自保存记录。当前仅支持在这台电脑上使用；邀请链接有效期为 7 天，不会发送邮件。</DialogDescription><form className="invite-form" onSubmit={e=>{e.preventDefault();void action(async()=>{setLink('');setCopied(false);const r=await api('/api/invitations','POST',{email});setLink(r.link);setEmail('');});}}><label className="form-field">受邀邮箱<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} disabled={busy}/></label><button className="primary" disabled={busy}>生成邀请链接</button></form>{link&&<div className="invite-result"><label className="form-field">一次性邀请链接<input readOnly value={link} onFocus={e=>e.target.select()}/></label><button className="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(link);setCopied(true);}catch{setError('请选中上面的链接手动复制');}}}><Copy size={15}/>{copied?'已复制':'复制链接'}</button></div>}{error&&<div className="error" role="alert">{error}</div>}<h3>本地账号</h3><div className="members-list">{data.users.map(u=><div className="member-row" key={u.id}><div><strong>{u.name}</strong><small>{u.email}</small><span>{u.role==='owner'?'管理员':u.active?'可使用':'已停用'}</span></div>{u.role!=='owner'&&<button className="secondary" disabled={busy} onClick={()=>action(async()=>{await api('/api/members','PATCH',{id:u.id,active:!u.active});})}>{u.active?'停用':'恢复'}</button>}</div>)}</div><h3>待接受邀请</h3>{data.invitations.length?data.invitations.map(i=><div className="member-row" key={i.id}><div><strong>{i.email}</strong><small>{i.expires>Date.now()?'到期：'+new Date(i.expires).toLocaleDateString('zh-CN'):'已过期，可重新邀请'}</small></div><button className="secondary" disabled={busy} onClick={()=>action(async()=>{await api('/api/invitations?id='+encodeURIComponent(i.id),'DELETE');setLink('');})}>撤销</button></div>):<p className="sub">暂无待接受邀请。</p>}</DialogContent></Dialog>;
}
createRoot(document.getElementById('root')!).render(<App/>);
