"use client";
import {useState,useEffect,useRef,useCallback} from 'react';
import {CalendarDays,CheckCheck,ChevronLeft,ChevronRight,FileText,LayoutDashboard,Lightbulb,ListTodo,LockKeyhole,Plus,Sparkles,Cloud,ArrowUpRight,NotebookPen,Pencil,Trash2,Download,Copy,RefreshCw,Clock3,X} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogClose} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogCancel} from '@/components/ui/alert-dialog';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Checkbox} from '@/components/ui/checkbox';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {SidebarProvider,Sidebar} from '@/components/ui/sidebar';
import {Empty} from '@/components/ui/empty';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {categories,kinds,ideaTypes,ideaTypeOf,entryDetails,today,monday,shift,validDate,validateEntry,makeReport,reportText,type Entry,type Kind,type Report} from '../lib/journal';
const navigation=['今日工作台','日程与计划','灵感收集箱','日报与周报'];
const icons=[LayoutDashboard,CalendarDays,Lightbulb,FileText];
type Data={entries:Entry[];ideas:Entry[];dates:string[];ideaCount:number;projects:string[]};
type Draft={id?:string;kind:Kind;title:string;body:string;date:string;time:string;category:string;done:boolean;projectName:string;ideaType:string;progress:number|null;problems:string;solution:string;nextSteps:string};
const blankData:Data={entries:[],ideas:[],dates:[],ideaCount:0,projects:[]};
function dateLabel(date:string){return new Date(date+'T12:00:00Z').toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long',timeZone:'UTC'});}
async function api(url:string,options?:RequestInit){const r=await fetch(url,{...options,headers:{'Content-Type':'application/json',...options?.headers}});const body:any=await r.json();if(!r.ok)throw new Error(body.error??'请求失败，请稍后重试');return body;}
function Picker({value,onChange,options,label}:{value:string;onChange:(x:string)=>void;options:string[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="choice"><SelectValue/></SelectTrigger><SelectContent position="popper">{options.map(x=><SelectItem value={x} key={x}>{x}</SelectItem>)}</SelectContent></Select>;}
function ViewTabs({value,onChange,items}:{value:string;onChange:(x:string)=>void;items:{value:string;label:string}[]}){return <Tabs value={value} onValueChange={onChange}><TabsList variant="line" className="tabs">{items.map(x=><TabsTrigger key={x.value} value={x.value} className={value===x.value?'active':''}>{x.label}</TabsTrigger>)}</TabsList></Tabs>;}
function EntryContent({entry:e}:{entry:Entry}){return <>{e.projectName&&<p className="project-label">项目 · {e.projectName}</p>}{e.kind!=='idea'&&e.progress!=null&&<div className="record-progress"><span>事项进度 {e.progress}%</span><progress max={100} value={e.progress} aria-label={e.title+'的事项进度'}/></div>}<dl className="record-details">{entryDetails(e).map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></>;}
function ReportBody({report,entries}:{report:Report;entries:Entry[]}){const weekly=report.from!==report.to;return <div className="report">
 <div className="report-overview"><p>{report.overview}</p></div>
 {report.projects.length>0&&<><h3>按项目汇总</h3>{report.projects.map(g=><section className="project-report" key={g.name}><h3>{g.name}<span className="count">{g.entries.length} 条记录</span></h3>{g.entries.map(e=><article className="report-entry" key={e.id}><h4>{e.title}</h4><div className="entry-meta"><span>{e.date}</span><span>{kinds[e.kind]}</span><span>{e.kind==='idea'?ideaTypeOf(e):e.done?'已完成':'待推进'}</span>{e.completedDate&&<span>完成于 {e.completedDate}</span>}</div><EntryContent entry={{...e,projectName:''}}/></article>)}</section>)}</>}
 <h3><CheckCheck size={18}/>已完成工作 <span className="count">{report.completed.length}</span></h3>{report.completed.length?<ul>{report.completed.map(e=><li key={e.id}>{e.title}<small>{e.projectName?' · '+e.projectName:''}{weekly?' · '+e.completedDate:''}</small></li>)}</ul>:<p>这段时间没有已完成的工作记录。</p>}
 <h3><ListTodo size={18}/>待推进事项 <span className="count">{report.pending.length}</span></h3>{report.pending.length?<ul>{report.pending.map(e=><li key={e.id}>{e.title}{e.nextSteps?'；下一步：'+e.nextSteps:''}<small> · {e.date}</small></li>)}</ul>:<p>这段时间没有待推进事项。</p>}
 <h3><Lightbulb size={18}/>灵感分类 <span className="count">{report.ideas.length}</span></h3>{report.ideaGroups.length?report.ideaGroups.map(g=><section key={g.name}><h3>{g.name}</h3><ul>{g.entries.map(e=><li key={e.id}>{e.title}<small> · {e.category}{e.projectName?' · '+e.projectName:''}</small></li>)}</ul></section>):<p>这段时间还没有收集灵感。</p>}
 {report.research.length>0&&<div className="report-group"><h3>科研进展</h3><ul>{report.research.map(e=><li key={e.id}>{e.title}{e.body?'：'+e.body:''}<small> · {e.done?'已完成':'进行中'} · {e.date}</small></li>)}</ul></div>}
 {report.groups.length>0&&<div className="report-group"><h3>按主题整理</h3>{report.groups.map(g=><div key={g.name}><h3>{g.name}<span className="count">{g.entries.length}</span></h3><p>{g.entries.map(e=>e.title).join('；')}</p></div>)}</div>}
 {weekly&&<div className="report-group"><h3>一周的每日小结</h3>{Array.from({length:7},(_,i)=>shift(report.from,i)).map(d=><div key={d}><h3>{dateLabel(d)}</h3><p>{makeReport(entries,d,d).overview}</p></div>)}</div>}
 <div className="report-group"><p className="report-method">按上海时区汇总当前已保存记录；同名项目合并展示，事项进度按记录日期保留。关键词分类可手动调整，修改记录后历史报表同步更新。</p></div>
 </div>;}
export default function Workspace({signedIn=false,accountTools,displayName='我'}:{signedIn?:boolean;accountTools?:React.ReactNode;displayName?:string}){
 const [view,setView]=useState(0),[date,setDate]=useState(today),[currentDay,setCurrentDay]=useState(today);
 const [data,setData]=useState<Data>(blankData),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [filter,setFilter]=useState('all'),[ideaCategory,setIdeaCategory]=useState('全部主题'),[ideaTypeFilter,setIdeaTypeFilter]=useState('全部灵感类型'),[quickType,setQuickType]=useState('自动分类'),[reportMode,setReportMode]=useState('daily'),[ideaOffset,setIdeaOffset]=useState(0);
 const [quick,setQuick]=useState(''),[draft,setDraft]=useState<Draft|null>(null),[formError,setFormError]=useState(''),[deleting,setDeleting]=useState<Entry|null>(null);
 const seq=useRef(0),busyRef=useRef(false),latest=useRef<any>(null);
 const start=monday(date),end=shift(start,6),days=Array.from({length:7},(_,i)=>shift(start,i));
 const dayEntries=data.entries.filter(e=>e.date===date||e.completedDate===date);
 const report=makeReport(data.entries,reportMode==='daily'?date:start,reportMode==='daily'?date:end);
 const daily=makeReport(data.entries,date,date);
 const loadData=useCallback(async(target:string,offset=0)=>{const ticket=++seq.current;setLoading(true);try{const from=monday(target);const d=await api('/api/entries?from='+from+'&to='+shift(from,6)+'&ideaOffset='+offset+'&ideaCategory='+encodeURIComponent(ideaCategory==='全部主题'?'':ideaCategory)+'&ideaType='+encodeURIComponent(ideaTypeFilter==='全部灵感类型'?'':ideaTypeFilter));if(ticket===seq.current){setData(d);setError('');}return d as Data;}catch(e){if(ticket===seq.current)setError((e as Error).message);throw e;}finally{if(ticket===seq.current)setLoading(false);}},[ideaCategory,ideaTypeFilter]);
 useEffect(()=>{if(signedIn)void loadData(date,ideaOffset).catch(()=>{});else setLoading(false);},[date,ideaOffset,signedIn,loadData]);
 useEffect(()=>{const id=setInterval(()=>{const next=today();if(next!==currentDay){setCurrentDay(next);setDate(d=>d===currentDay?next:d);}},30000);return()=>clearInterval(id);},[currentDay]);
 const saveRecord=async(input:Partial<Draft>,method='POST')=>{
  if(busyRef.current)throw new Error('正在保存上一条记录，请稍候');
  busyRef.current=true;setBusy(true);
  try{const result=await api('/api/entries',{method,body:JSON.stringify(input)});await loadData(date,ideaOffset).catch(()=>{toast.error('记录已保存，但刷新失败，请点击重试');});return result.entry as Entry;}
  finally{busyRef.current=false;setBusy(false);}
 };
 const openNew=(kind:Kind='plan')=>{setFormError('');setDraft({kind,title:'',body:'',date,time:'',category:kind==='research'?'科研进展':'自动分类',done:false,projectName:'',ideaType:'自动分类',progress:null,problems:'',solution:'',nextSteps:''});};
 const edit=(e:Entry)=>{setFormError('');setDraft({...e});};
 const toggle=async(e:Entry)=>{try{await saveRecord({id:e.id,done:!e.done},'PATCH');toast.success(e.done?'已标为待完成':'已完成，日报已更新');}catch(e){toast.error((e as Error).message);}};
 const saveDraft=async(event:React.FormEvent)=>{event.preventDefault();if(!draft)return;setFormError('');try{validateEntry(draft);await saveRecord(draft,draft.id?'PATCH':'POST');setDraft(null);toast.success('已保存，日报与周报已同步更新');}catch(e){setFormError((e as Error).message);}};
 const saveIdea=async()=>{if(!quick.trim())return;const text=quick.trim();try{await saveRecord({kind:'idea',title:text.slice(0,100),body:text.length>100?text:'',date,time:'',category:'自动分类',ideaType:quickType,done:false});setQuick('');toast.success('灵感已收好');}catch(e){toast.error((e as Error).message);}};
 const remove=async()=>{if(!deleting||busyRef.current)return;busyRef.current=true;setBusy(true);try{await api('/api/entries?id='+encodeURIComponent(deleting.id),{method:'DELETE'});setDeleting(null);await loadData(date,ideaOffset);toast.success('记录已删除，汇总已更新');}catch(e){toast.error((e as Error).message);}finally{busyRef.current=false;setBusy(false);}};
 const go=(n:number)=>{setView(n);setFilter('all');window.scrollTo({top:0});};
 const visibleEntries=(view===1?data.entries.filter(e=>e.date>=start&&e.date<=end):dayEntries).filter(e=>e.kind!=='idea').filter(e=>filter==='all'||(filter==='done'?e.done:!e.done)).sort((a,b)=>a.date.localeCompare(b.date)||a.time.localeCompare(b.time)||a.createdAt.localeCompare(b.createdAt));
 const ideas=data.ideas;
 const archiveDates=[...new Set([date,...data.dates])].sort().reverse();
 const archive=reportMode==='daily'?archiveDates:[...new Set(archiveDates.map(monday))];
 const authGuard=!signedIn||loading;
 latest.current={date,data,saveRecord,loadData};
 useEffect(()=>{
  const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();
  const register=(tool:any)=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
  register({name:'create_record',title:'创建日序记录',description:'保存一条日程、计划、工作、灵感或科研记录到当前用户的本地空间，更新工作台。',inputSchema:{type:'object',properties:{kind:{type:'string',enum:['plan','event','work','idea','research']},title:{type:'string',minLength:1,maxLength:300},body:{type:'string',maxLength:10000},projectName:{type:'string',maxLength:120},ideaType:{type:'string',enum:['自动分类',...ideaTypes]},progress:{type:'integer',minimum:0,maximum:100},problems:{type:'string',maxLength:10000},solution:{type:'string',maxLength:10000},nextSteps:{type:'string',maxLength:10000},done:{type:'boolean'},date:{type:'string',pattern:'^\\d{4}-\\d{2}-\\d{2}$'},time:{type:'string'},category:{type:'string',enum:['自动分类',...categories]}},required:['kind','title','date'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:unknown)=>{const v=validateEntry(input);const e=await latest.current.saveRecord(v);toast.success('记录已保存');return {id:e.id,category:e.category,date:e.date};}});
  register({name:'read_current_report',title:'读取当前日报或周报',description:'按当前选中的日期读取本地日报或所在周的周报。',inputSchema:{type:'object',properties:{period:{type:'string',enum:['daily','weekly']}},required:['period'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(input:any)=>{if(!input||!['daily','weekly'].includes(input.period))throw new Error('period 必须是 daily 或 weekly');const d=latest.current.date;const state=await latest.current.loadData(d);return makeReport(state.entries,input.period==='daily'?d:monday(d),input.period==='daily'?d:shift(monday(d),6));}});
  return()=>lifecycle.abort();
 },[]);
 const entryActions=(e:Entry)=><div className="entry-actions"><button className="iconbtn" aria-label={'编辑 '+e.title} onClick={()=>edit(e)} disabled={busy}><Pencil/></button><button className="iconbtn" aria-label={'删除 '+e.title} onClick={()=>setDeleting(e)} disabled={busy}><Trash2/></button></div>;
 const entryList=<>{loading?<Empty className="empty"><p>正在读取记录…</p></Empty>:visibleEntries.length?visibleEntries.map(e=><div className={'entry '+(e.done?'done':'')} key={e.id}>{<Checkbox className={'check '+(e.done?'checked':'')} checked={e.done} disabled={busy} onCheckedChange={()=>toggle(e)} aria-label={(e.done?'取消完成 ':'完成 ')+e.title}/>}<div className="entry-body"><h3>{e.title}</h3><EntryContent entry={e}/><div className="entry-meta">{(view===1||e.date!==date)&&<span>{e.date}</span>}{e.time&&<span><Clock3 size={12} style={{display:'inline',verticalAlign:'middle'}}/> {e.time}</span>}<span className="tag">{e.category}</span><span>{kinds[e.kind]}</span>{e.done&&<span>完成于 {e.completedDate}</span>}</div></div>{entryActions(e)}</div>):<Empty className="empty"><div className="empty-icon"><CalendarDays size={23}/></div><p>{filter==='done'?'完成的每一件事，都会留在这里':filter==='pending'?'当前没有待完成事项':'今天的计划，从第一件小事开始'}</p><button className="secondary" onClick={()=>openNew('plan')} disabled={!signedIn}><Plus size={15}/>添加计划</button></Empty>}</>;
 return <SidebarProvider className="app"><Sidebar collapsible="none" className="sidebar"><div className="brand"><div className="brand-mark"><NotebookPen size={22}/></div><div><strong>日序</strong><small>DAYFOLIO</small></div></div><p className="nav-label">我的空间</p><nav className="nav" aria-label="主要导航">{navigation.map((x,i)=>{const Icon=icons[i];return <button key={x} onClick={()=>go(i)} aria-current={view===i?'page':undefined} className={view===i?'active':''}><Icon/>{x}</button>})}</nav><div className="sidebar-bottom"><div className="private"><LockKeyhole size={14}/>按账号独立保存</div><div className="profile"><span className="avatar">我</span><div><strong>{displayName}</strong><small>记录每一点进展</small></div></div></div></Sidebar><main className="main"><div className="topbar"><span><b className="mobile-brand">日序</b><span className="crumb">我的空间 / </span>{navigation[view]}</span><span className="sync" aria-live="polite"><Cloud size={15}/>{busy?'正在保存…':loading?'读取记录中…':signedIn?(error?'尚未同步':'已与本地同步'):'个人本地笔记'}</span></div><div className="account-toolbar">{accountTools}</div><div className="intro"><div><p className="eyebrow">{view===0?date.slice(0,4)+' 年 · '+dateLabel(date):view===1?start+' — '+end:view===2?'留住那些一闪而过的念头':'每日有所获，每周有所进'}</p><h1>{view===0?(date===currentDay?'今天，循序向前。':'这一天的足迹。'):navigation[view]}</h1><p className="sub">{['把计划落在今天，把灵感留给未来。','为重要的事留出时间，让计划一步步发生。','先记下来，再让想法慢慢生长。','记录自动汇成日报，一周的进展也清晰可见。'][view]}</p></div><button className="primary" onClick={()=>openNew(view===2?'idea':'plan')} disabled={!signedIn}><Plus size={17}/>{view===2?'记录灵感':'新建记录'}</button></div>{!signedIn&&<div className="signin"><span>登录后即可保存和查看你的个人记录。</span><a href="#" target="_top">返回登录</a></div>}{error&&<div className="error" role="alert">{error} <button onClick={()=>loadData(date,ideaOffset).catch(()=>{})} className="text-btn"><RefreshCw size={14}/>重试</button></div>}
 {(view===0||view===1)&&<><div className="datebar"><button className="iconbtn" aria-label="上一周" onClick={()=>setDate(shift(date,-7))}><ChevronLeft/></button><div className="weekstrip">{days.map((d,i)=><button className={'day '+(d===date?'selected':'')} aria-label={d} aria-pressed={d===date} onClick={()=>setDate(d)} key={d}><span>周{'一二三四五六日'[i]}</span><b>{Number(d.slice(-2))}</b></button>)}</div><button className="iconbtn" aria-label="下一周" onClick={()=>setDate(shift(date,7))}><ChevronRight/></button></div><div className="view-toolbar compact-toolbar"><input type="date" aria-label="选择日期" min="2000-01-01" max="2100-12-31" value={date} onChange={e=>validDate(e.target.value)&&setDate(e.target.value)}/><button className="text-btn" onClick={()=>setDate(currentDay)}>回到今天</button><span>上海时区</span></div></>}
 {view===0&&<div className="metrics">{['今日计划','已完成','捕捉灵感','计划完成率'].map((x,i)=>{const Icon=[ListTodo,CheckCheck,Lightbulb,CalendarDays][i];return <div className="metric" key={x}><div><p>{x}</p><b>{[daily.planned.length,daily.completed.length,daily.ideas.length,daily.rate][i]}</b><small>{i===3?'%':i===2?'条':'项'}</small></div><span className="metric-icon"><Icon size={21}/></span></div>})}</div>}
 {(view===0||view===1)&&<div className={view===0?'grid':''}><section><div className="panel"><div className="panel-head"><h2>{view===0?'今日安排与工作':'本周日程与计划'} <span className="count">{visibleEntries.length}</span></h2><button className="text-btn" onClick={()=>openNew('event')} disabled={!signedIn}><Plus size={15}/>添加安排</button></div><ViewTabs value={filter} onChange={setFilter} items={[{value:'all',label:'全部事项'},{value:'pending',label:'待完成'},{value:'done',label:'已完成'}]}/>{entryList}</div>{view===0&&<div className="panel"><div className="panel-head"><h2>今日灵感 <span className="count">{daily.ideas.length}</span></h2><button className="text-btn" onClick={()=>go(2)}>全部灵感 <ArrowUpRight size={14}/></button></div>{daily.ideas.length?daily.ideas.slice(0,4).map(e=><div className="idea-row" key={e.id}><p>{e.title}</p><div className="entry-meta"><span className="tag">{ideaTypeOf(e)}</span><span>{e.projectName||e.category}</span><button className="text-btn" onClick={()=>edit(e)}>查看</button></div></div>):<Empty className="empty small-empty"><Lightbulb size={22}/><p>想到什么，就随手记下来。</p></Empty>}</div>}</section>{view===0&&<section><div className="panel"><div className="panel-head"><h2><Lightbulb size={18} color="#ac8fce"/>灵感速记</h2><span className="count">随时记录</span></div><div className="quick"><div className="quick-type"><Picker value={quickType} onChange={setQuickType} options={["自动分类",...ideaTypes]} label="速记灵感分类"/></div><textarea aria-label="灵感内容" value={quick} maxLength={10000} onChange={e=>setQuick(e.target.value)} placeholder="突然想到…… 一个想法，一个问题，或一种新的可能。"/><div className="quick-footer"><span>主题按关键词整理</span><button className="primary" disabled={busy||!signedIn||!quick.trim()} onClick={saveIdea}>记下来 <ArrowUpRight size={15}/></button></div></div></div><div className="summary"><div className="summary-head"><h2><Sparkles size={18}/>今日小结</h2><span className="auto">自动汇总</span></div><p>{daily.overview}</p><button className="text-btn" onClick={()=>{setReportMode('daily');go(3);}}>查看完整日报 <ArrowUpRight size={14}/></button></div><div className="panel"><div className="panel-head"><h2>今日分类</h2><span className="count">{daily.total} 项</span></div><div className="category">{categories.map(x=>{const n=daily.groups.find(g=>g.name===x)?.entries.length??0;return <div className="cat-row" key={x}><span>{x}</span><div className="cat-bar"><div style={{width:(daily.total?n/daily.total*100:0)+'%'}}/></div><span>{n}</span></div>})}</div></div></section>}</div>}
 {view===2&&<><div className="view-toolbar"><Picker value={ideaTypeFilter} onChange={x=>{setIdeaOffset(0);setIdeaTypeFilter(x);}} label="筛选灵感类型" options={["全部灵感类型",...ideaTypes]}/><Picker value={ideaCategory} onChange={x=>{setIdeaOffset(0);setIdeaCategory(x);}} label="筛选灵感主题" options={["全部主题",...categories]}/><span className="sub">共 {data.ideaCount} 条灵感 · 本页 {ideas.length} 条</span></div>{loading?<Empty className="empty"><p>正在打开灵感收集箱…</p></Empty>:ideas.length?<div className="idea-grid">{ideas.map(e=><article className="idea-card" key={e.id}><div className="entry-meta" style={{margin:'0 0 13px'}}><span className="tag">{ideaTypeOf(e)}</span><span>{e.category}</span><span>{e.date}</span></div><h3>{e.title}</h3><EntryContent entry={e}/>{entryActions(e)}</article>)}</div>:<div className="panel"><Empty className="empty"><div className="empty-icon"><Lightbulb/></div><p>这里留给下一个好想法。</p><button className="secondary" disabled={!signedIn} onClick={()=>openNew('idea')}><Plus size={15}/>记录灵感</button></Empty></div>}<div className="view-toolbar pagination"><button className="secondary" disabled={ideaOffset===0||loading} onClick={()=>setIdeaOffset(o=>Math.max(0,o-60))}>上一页</button><span>第 {Math.floor(ideaOffset/60)+1} 页</span><button className="secondary" disabled={ideaOffset+60>=data.ideaCount||loading} onClick={()=>setIdeaOffset(o=>o+60)}>下一页</button></div></>}
 {view===3&&<><div className="view-toolbar"><ViewTabs value={reportMode} onChange={setReportMode} items={[{value:'daily',label:'每日日报'},{value:'weekly',label:'每周周报'}]}/><input type="date" aria-label="报表日期" min="2000-01-01" max="2100-12-31" value={date} onChange={e=>validDate(e.target.value)&&setDate(e.target.value)}/><span className="sub">周一至周日 · 上海时区</span></div><div className="report-layout"><aside className="report-list" aria-label="历史报表">{archive.slice(0,30).map(d=><button key={d} onClick={()=>setDate(d)} className={(reportMode==='daily'?date:start)===d?'active':''}>{d}{reportMode==='weekly'?' 起的一周':''}<small>{reportMode==='daily'?'每日记录汇总':'一周工作与灵感'}</small></button>)}</aside><section className="panel"><div className="panel-head"><h2>{reportMode==='daily'?'日报':'周报'} <span className="count">{report.from}{reportMode==='weekly'?' — '+report.to:''}</span></h2><div className="entry-actions"><button className="iconbtn" aria-label="复制报表" disabled={authGuard||!!error} onClick={async()=>{try{await navigator.clipboard.writeText(reportText(report));toast.success('报表已复制');}catch{toast.error('复制失败，请使用下载报表');}}}><Copy/></button><button className="iconbtn" aria-label="下载报表" disabled={authGuard||!!error} onClick={()=>{const u=URL.createObjectURL(new Blob([reportText(report)],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download='日序-'+(reportMode==='daily'?'日报':'周报')+'-'+report.from+'.md';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}}><Download/></button></div></div>{loading?<Empty className="empty"><p>正在整理记录…</p></Empty>:<ReportBody report={report} entries={data.entries}/>}</section></div></>}
 <p className="footer-note">每一条记录，都会成为下一步的线索。</p></main>
 <Dialog open={!!draft} onOpenChange={open=>{if(!open&&!busy)setDraft(null);}}><DialogContent className="modal record-modal" showCloseButton={false}>
 <div className="modal-head"><DialogTitle>{draft?.id?'编辑记录':'新建记录'}</DialogTitle><DialogClose asChild><button aria-label="关闭编辑" className="iconbtn" disabled={busy}><X/></button></DialogClose></div>
 <DialogDescription className="sr-only">填写记录内容，可关联项目并记录进度、问题和下一步，保存后自动更新报表。</DialogDescription>
 {draft&&<form onSubmit={saveDraft}><fieldset disabled={busy} className="record-fields">
 <div className="form-row"><div className="form-field"><span>记录类型</span><Picker label="记录类型" value={kinds[draft.kind]} options={Object.values(kinds)} onChange={x=>{const kind=Object.keys(kinds).find(k=>kinds[k as Kind]===x) as Kind;setDraft({...draft,kind,category:kind==='research'?'科研进展':draft.category,done:kind==='idea'?false:draft.done,progress:kind==='idea'?null:draft.progress});}}/></div><label className="form-field">记录日期<input type="date" required min="2000-01-01" max="2100-12-31" value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></label></div>
 <label className="form-field">{draft.kind==='idea'?'想法标题':'记录标题'}<input autoFocus required maxLength={300} value={draft.title} placeholder={draft.kind==='idea'?'一个值得留下的想法':'今天准备做什么，或推进了什么？'} onChange={e=>setDraft({...draft,title:e.target.value})}/></label>
 <label className="form-field">项目／课题名称（可选）<input list="project-names" maxLength={120} value={draft.projectName} placeholder="例如：多模态检索课题" onChange={e=>setDraft({...draft,projectName:e.target.value})}/><datalist id="project-names">{data.projects.map(name=><option value={name} key={name}/>)}</datalist><small>同名项目会在日报、周报中归到一起；可选择已有名称。</small></label>
 {draft.kind==='idea'&&<div className="form-field"><span>灵感分类</span><Picker value={draft.ideaType||'自动分类'} onChange={ideaType=>setDraft({...draft,ideaType})} label="灵感分类" options={['自动分类',...ideaTypes]}/><small>{({'灵感火花':'突然想到的点子、新方向或创意。','问题与解决方案':'记录问题、排查过程以及最终有效的做法。','工作／科研思路':'记录推进路径、实验设计或实现方案。','待验证假设':'记录猜想、验证方法以及什么结果能支持它。','资料与方法':'记录有用的文献、工具、链接和可复用方法。'} as Record<string,string>)[draft.ideaType]||'按标题和内容中的关键词分类，也可以手动选择。'}</small></div>}
 <section className="form-section"><h3>{draft.kind==='research'?'科研进展':draft.kind==='idea'?'想法内容':'内容与进展'}</h3><label className="form-field">{draft.kind==='research'?'科研进展内容':draft.kind==='idea'?'详细内容':'详细内容／本次成果'}<textarea rows={4} maxLength={10000} value={draft.body} placeholder={draft.kind==='research'?'记录实验设置、结果、论文进展或本次结论…':'记录具体内容、已做的事和关键结果…'} onChange={e=>setDraft({...draft,body:e.target.value})}/></label>
 {draft.kind!=='idea'&&<div className="form-row progress-fields"><label className="form-field">事项进度（%，可选）<input type="number" min={0} max={100} step={1} value={draft.progress??''} placeholder="0–100" onChange={e=>{const progress=e.target.value===''?null:Number(e.target.value);setDraft({...draft,progress,done:progress===100});}}/></label><label className="completion-field"><Checkbox checked={draft.done} onCheckedChange={checked=>setDraft({...draft,done:checked===true,progress:checked===true?100:null})}/>已完成本条事项</label></div>}
 </section><section className="form-section"><h3>问题与行动</h3><label className="form-field">遇到的问题（可选）<textarea rows={2} maxLength={10000} value={draft.problems} placeholder="卡在哪里？哪些问题还没有解决？" onChange={e=>setDraft({...draft,problems:e.target.value})}/></label><label className="form-field">解决方案（可选）<textarea rows={2} maxLength={10000} value={draft.solution} placeholder="尝试过什么？有效的做法或待尝试方案是什么？" onChange={e=>setDraft({...draft,solution:e.target.value})}/></label><label className="form-field">下一步（可选）<textarea rows={2} maxLength={10000} value={draft.nextSteps} placeholder="接下来具体做什么，如何验证？" onChange={e=>setDraft({...draft,nextSteps:e.target.value})}/></label></section>
 <div className="form-row"><div className="form-field"><span>主题分类</span><Picker value={draft.category} onChange={category=>setDraft({...draft,category})} label="主题分类" options={['自动分类',...categories]}/></div><label className="form-field">时间（可选）<input type="time" value={draft.time} onChange={e=>setDraft({...draft,time:e.target.value})}/></label></div>
 <p className="sub">每天为同一项目新增一条记录，可以在周报中看到连续进展。</p>
 </fieldset>{formError&&<div className="error" role="alert" style={{marginTop:14}}>{formError}</div>}<div className="form-actions"><DialogClose asChild><button type="button" className="secondary" disabled={busy}>取消</button></DialogClose><button className="primary" type="submit" disabled={busy}>{busy?'保存中…':'保存记录'}</button></div></form>}
 </DialogContent></Dialog>
 <AlertDialog open={!!deleting} onOpenChange={open=>{if(!open&&!busy)setDeleting(null);}}><AlertDialogContent className="modal"><AlertDialogTitle>删除这条记录？</AlertDialogTitle><AlertDialogDescription>“{deleting?.title}”将被删除，相关日报与周报也会更新。</AlertDialogDescription><div className="form-actions"><AlertDialogCancel className="secondary" disabled={busy}>保留记录</AlertDialogCancel><button className="primary danger" disabled={busy} onClick={remove}>{busy?'删除中…':'确认删除'}</button></div></AlertDialogContent></AlertDialog><Toaster theme="light" position="bottom-center"/></SidebarProvider>;
}



